# Build for darwin, linux and windows
builds:
  - main: ./cmd/twenty48
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - 386
      - amd64

# Make release files look nice
archive:
  replacements:
    386: 32-bit
    amd64: 64-bit
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
  files:
    - LICENSE

# Do not publish the release yet
release:
  draft: true
  name_template: "v{{.Version}}"
