# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9

    working_directory: /go/src/github.com/alyyousuf7/twenty48

    steps:
      - checkout
      - run:
          name: Run unit tests
          command: go test -v ./...
      - run:
          name: Build binary
          command: go build -v ./cmd/twenty48/...
      - run:
          name: Generate coverage report
          command: |
            for pkg in $(go list ./... | grep -v /vendor/); do
              go test -race -coverprofile=../../../$pkg/coverage.txt -covermode=atomic $pkg || exit;
            done
      - run:
          name: Upload coverage report to codecov
          command: bash <(curl -s https://codecov.io/bash)